server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: IAM-SERVICE
          uri: lb://IAM-SERVICE
          predicates:
            - Path=/users/**

        - id: PHOTO-SERVICE
          uri: lb://PHOTO-SERVICE
          predicates:
            - Path=/photos/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka